//
//  CloudLogicViewController.h
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.6
//
#import <UIKit/UIKit.h>

@interface CloudLogicViewController : UIViewController

@property (weak, nonatomic) IBOutlet UIButton *resetButton;
@property (weak, nonatomic) IBOutlet UIButton *invokeButton;
@property (weak, nonatomic) IBOutlet UITextView *requestTextView;
@property (weak, nonatomic) IBOutlet UITextView *resultTextView;
@property (weak, nonatomic) IBOutlet UITextField *functionField;

- (IBAction)handleReset:(id)sender;
- (IBAction)handleInvoke:(id)sender;
- (IBAction)tapRecognized:(UITapGestureRecognizer *)sender;

@end
