//
//  SignInViewController.h
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.6
//
//
#import <UIKit/UIKit.h>

@interface SignInViewController : UIViewController

@property (weak, nonatomic) IBOutlet UIView *anchorView;

@property (weak, nonatomic) IBOutlet UIButton *facebookButton;
// Support code for Google provider UI.
@property (weak, nonatomic) IBOutlet UIButton *googleButton;
@property (weak, nonatomic) IBOutlet UIButton *customProviderButton;
@property (weak, nonatomic) IBOutlet UIButton *siginBtn;
@property (weak, nonatomic) IBOutlet UIButton *ressetPwdBtnBtn;
@property (weak, nonatomic) IBOutlet UIButton *userPwdBtnBtn;
@property (weak, nonatomic) IBOutlet UIButton *vendorPwdBtnBtn;
@property (weak, nonatomic) IBOutlet UIButton *customCreateAccountButton;
@property (weak, nonatomic) IBOutlet UIButton *customForgotPasswordButton;
@property (weak, nonatomic) IBOutlet UITextField *customUserIdField;
@property (weak, nonatomic) IBOutlet UITextField *customPasswordField;
@property (weak, nonatomic) IBOutlet UIView *leftHorizontalBar;
@property (weak, nonatomic) IBOutlet UIView *rightHorizontalBar;
@property (weak, nonatomic) IBOutlet UILabel *orSignInWithLabel;


@end
