//
//  SignInViewController.h
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.6
//
//
#import <UIKit/UIKit.h>
#import "NIDropDown.h"
#import "MBProgressHUD.h"
#import <MapKit/MapKit.h>

@interface SignInViewController : UIViewController<UITextViewDelegate, NIDropDownDelegate, CLLocationManagerDelegate,MKMapViewDelegate>{
    UITextField *mytextField;
    NIDropDown *dropDown;
    NSString *tipoSelected;
    CLLocationManager *locationManager;
    MKPointAnnotation *origen, *driver, *destino;
    CLLocation *location;
    BOOL bandera;
}
@property (weak, nonatomic) IBOutlet UIButton *selectLocationBtn;

@property (weak, nonatomic) IBOutlet UIView *anchorView;
@property (weak, nonatomic) IBOutlet UIButton *selectButton;
@property (weak, nonatomic) IBOutlet UIButton *facebookButton;
@property (weak, nonatomic) IBOutlet UIScrollView *myscroll;
// Support code for Google provider UI.
@property (weak, nonatomic) IBOutlet UIButton *googleButton;
@property (weak, nonatomic) IBOutlet UIButton *customProviderButton;
@property (weak, nonatomic) IBOutlet UIButton *siginBtn;
@property (weak, nonatomic) IBOutlet UIButton *ressetPwdBtnBtn;
@property (weak, nonatomic) IBOutlet UIButton *userPwdBtnBtn;
@property (weak, nonatomic) IBOutlet UIButton *vendorPwdBtnBtn;
@property (weak, nonatomic) IBOutlet UIButton *customCreateAccountButton;
@property (weak, nonatomic) IBOutlet UIButton *customForgotPasswordButton;
@property (weak, nonatomic) IBOutlet UITextField *customUserIdField;
@property (weak, nonatomic) IBOutlet UITextField *customPasswordField;
@property (weak, nonatomic) IBOutlet UIView *leftHorizontalBar;
@property (weak, nonatomic) IBOutlet UIView *rightHorizontalBar;
@property (weak, nonatomic) IBOutlet UILabel *orSignInWithLabel;
@property (weak, nonatomic) IBOutlet UITextField *firstName;
@property (weak, nonatomic) IBOutlet UITextField *lastName;
@property (weak, nonatomic) IBOutlet UITextField *email;
@property (weak, nonatomic) IBOutlet UITextField *location;
@property (weak, nonatomic) IBOutlet UITextField *password;
@property (strong, nonatomic) MBProgressHUD *progressHUD;
@property (weak, nonatomic) IBOutlet UITextField *emailLogin;
@property (weak, nonatomic) IBOutlet UITextField *passwordLogin;
@property (weak, nonatomic) IBOutlet UITextField *businessName;
@property (weak, nonatomic) IBOutlet UITextField *Username;
@property (weak, nonatomic) IBOutlet MKMapView *mvMap;
@property (weak, nonatomic) IBOutlet UIImageView *pin;


@end
